settings:
  app:
    name: Mercury
    version: v0.1.0

  connection:
    port: 8080

  data:
    temp-unit: celsius  # [fahrenheit | celsius]
    pressure-unit: psi  # [psi | kPa]
    speed-unit: mph  # [mph | kph]
    max-rpm: 13500

  display:
    port: 5000
    refresh-rate: 1.4  # seconds